
#Все настройки, связанные с основным игровым процессом
[gameplay]
	#Создавать ли корабли снабжения и лагеря c сундуками. [По умолчанию: true]
	generatesupplyloot = true

#Все настройки, связанные с системой запросов
[requestsystem]
	#Следует ли системе запросов отображать отладочную информацию в debug.log? Полезно при сбоях. [По умолчанию: false]
	enabledebuglogging = false

